
package lt.viko.restaurant_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RestaurantPort", targetNamespace = "http://www.viko.lt/restaurant-service")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RestaurantPort {


    /**
     * 
     * @param getMenuRequest
     * @return
     *     returns lt.viko.restaurant_service.GetMenuResponse
     */
    @WebMethod
    @WebResult(name = "getMenuResponse", targetNamespace = "http://www.viko.lt/restaurant-service", partName = "getMenuResponse")
    @Action(input = "http://www.viko.lt/restaurant-service/RestaurantPort/getMenuRequest", output = "http://www.viko.lt/restaurant-service/RestaurantPort/getMenuResponse")
    public GetMenuResponse getMenu(
        @WebParam(name = "getMenuRequest", targetNamespace = "http://www.viko.lt/restaurant-service", partName = "getMenuRequest")
        GetMenuRequest getMenuRequest);

    /**
     * 
     * @param getAllRestaurantsRequest
     * @return
     *     returns lt.viko.restaurant_service.GetAllRestaurantsResponse
     */
    @WebMethod
    @WebResult(name = "getAllRestaurantsResponse", targetNamespace = "http://www.viko.lt/restaurant-service", partName = "getAllRestaurantsResponse")
    @Action(input = "http://www.viko.lt/restaurant-service/RestaurantPort/getAllRestaurantsRequest", output = "http://www.viko.lt/restaurant-service/RestaurantPort/getAllRestaurantsResponse")
    public GetAllRestaurantsResponse getAllRestaurants(
        @WebParam(name = "getAllRestaurantsRequest", targetNamespace = "http://www.viko.lt/restaurant-service", partName = "getAllRestaurantsRequest")
        GetAllRestaurantsRequest getAllRestaurantsRequest);

    /**
     * 
     * @param getRestaurantRequest
     * @return
     *     returns lt.viko.restaurant_service.GetRestaurantResponse
     */
    @WebMethod
    @WebResult(name = "getRestaurantResponse", targetNamespace = "http://www.viko.lt/restaurant-service", partName = "getRestaurantResponse")
    @Action(input = "http://www.viko.lt/restaurant-service/RestaurantPort/getRestaurantRequest", output = "http://www.viko.lt/restaurant-service/RestaurantPort/getRestaurantResponse")
    public GetRestaurantResponse getRestaurant(
        @WebParam(name = "getRestaurantRequest", targetNamespace = "http://www.viko.lt/restaurant-service", partName = "getRestaurantRequest")
        GetRestaurantRequest getRestaurantRequest);

}
