
package lt.viko.eif.dalencinovic.first.spring.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RestaurantWebService", targetNamespace = "http://service.spring.first.dalencinovic.eif.viko.lt/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RestaurantWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns lt.viko.eif.dalencinovic.first.spring.service.Restaurant
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRestaurant", targetNamespace = "http://service.spring.first.dalencinovic.eif.viko.lt/", className = "lt.viko.eif.dalencinovic.first.spring.service.GetRestaurant")
    @ResponseWrapper(localName = "getRestaurantResponse", targetNamespace = "http://service.spring.first.dalencinovic.eif.viko.lt/", className = "lt.viko.eif.dalencinovic.first.spring.service.GetRestaurantResponse")
    @Action(input = "http://service.spring.first.dalencinovic.eif.viko.lt/RestaurantWebService/getRestaurantRequest", output = "http://service.spring.first.dalencinovic.eif.viko.lt/RestaurantWebService/getRestaurantResponse")
    public Restaurant getRestaurant(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<lt.viko.eif.dalencinovic.first.spring.service.MenuItem>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMenu", targetNamespace = "http://service.spring.first.dalencinovic.eif.viko.lt/", className = "lt.viko.eif.dalencinovic.first.spring.service.GetMenu")
    @ResponseWrapper(localName = "getMenuResponse", targetNamespace = "http://service.spring.first.dalencinovic.eif.viko.lt/", className = "lt.viko.eif.dalencinovic.first.spring.service.GetMenuResponse")
    @Action(input = "http://service.spring.first.dalencinovic.eif.viko.lt/RestaurantWebService/getMenuRequest", output = "http://service.spring.first.dalencinovic.eif.viko.lt/RestaurantWebService/getMenuResponse")
    public List<MenuItem> getMenu(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @return
     *     returns java.util.List<lt.viko.eif.dalencinovic.first.spring.service.Restaurant>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllRestaurants", targetNamespace = "http://service.spring.first.dalencinovic.eif.viko.lt/", className = "lt.viko.eif.dalencinovic.first.spring.service.GetAllRestaurants")
    @ResponseWrapper(localName = "getAllRestaurantsResponse", targetNamespace = "http://service.spring.first.dalencinovic.eif.viko.lt/", className = "lt.viko.eif.dalencinovic.first.spring.service.GetAllRestaurantsResponse")
    @Action(input = "http://service.spring.first.dalencinovic.eif.viko.lt/RestaurantWebService/getAllRestaurantsRequest", output = "http://service.spring.first.dalencinovic.eif.viko.lt/RestaurantWebService/getAllRestaurantsResponse")
    public List<Restaurant> getAllRestaurants();

}
