
package lt.viko.eif.dalencinovic.first.spring.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RestaurantWebServiceImplService", targetNamespace = "http://service.spring.first.dalencinovic.eif.viko.lt/", wsdlLocation = "http://localhost:8090/ws/restaurant?wsdl")
public class RestaurantWebServiceImplService
    extends Service
{

    private final static URL RESTAURANTWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RESTAURANTWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName RESTAURANTWEBSERVICEIMPLSERVICE_QNAME = new QName("http://service.spring.first.dalencinovic.eif.viko.lt/", "RestaurantWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/ws/restaurant?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RESTAURANTWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        RESTAURANTWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public RestaurantWebServiceImplService() {
        super(__getWsdlLocation(), RESTAURANTWEBSERVICEIMPLSERVICE_QNAME);
    }

    public RestaurantWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RESTAURANTWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public RestaurantWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, RESTAURANTWEBSERVICEIMPLSERVICE_QNAME);
    }

    public RestaurantWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RESTAURANTWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public RestaurantWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RestaurantWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RestaurantWebService
     */
    @WebEndpoint(name = "RestaurantWebServiceImplPort")
    public RestaurantWebService getRestaurantWebServiceImplPort() {
        return super.getPort(new QName("http://service.spring.first.dalencinovic.eif.viko.lt/", "RestaurantWebServiceImplPort"), RestaurantWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RestaurantWebService
     */
    @WebEndpoint(name = "RestaurantWebServiceImplPort")
    public RestaurantWebService getRestaurantWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.spring.first.dalencinovic.eif.viko.lt/", "RestaurantWebServiceImplPort"), RestaurantWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RESTAURANTWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw RESTAURANTWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return RESTAURANTWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
